<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>15</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RootNamespace>Starlight.Launcher.WebUI</RootNamespace>
        <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MudBlazor" Version="9.7.0" />
      <PackageReference Include="MudBlazor.Markdown" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

</Project>
